# Generated by Django 6.0 on 2025-12-09 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_indicatordata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicatordata',
            unique_together={('country', 'indicator_code', 'year')},
        ),
    ]
